// 100 buku self-development & bisnis — kurasi Mote Kreatif.
// cover: Open Library (sementara). url: link affiliate Shopee — DIISI MANUAL.

export type BookCategory =
  | "uang"
  | "kebiasaan"
  | "mindset"
  | "bisnis"
  | "kepemimpinan"
  | "marketing"
  | "komunikasi"
  | "wawasan"
  ;

export type Book = {
  title: string;
  author: string;
  category: BookCategory;
  hook: string;
  cover: string;
  url: string;
  featured?: boolean;
};

export const BOOK_CATEGORIES: { key: BookCategory; label: string }[] = [
  { key: "uang", label: "Uang & Finansial" },
  { key: "kebiasaan", label: "Kebiasaan & Produktivitas" },
  { key: "mindset", label: "Mindset & Psikologi" },
  { key: "bisnis", label: "Bisnis & Startup" },
  { key: "kepemimpinan", label: "Kepemimpinan" },
  { key: "marketing", label: "Marketing & Sales" },
  { key: "komunikasi", label: "Komunikasi & Relasi" },
  { key: "wawasan", label: "Hidup & Wawasan" },
];

export const BOOKS: Book[] = [
  {
    title: "The Psychology of Money",
    author: "Morgan Housel",
    category: "uang",
    hook: "Kenapa orang pintar bisa bangkrut dan orang biasa bisa kaya — soal perilaku, bukan rumus.",
    cover: "https://covers.openlibrary.org/b/id/10389354-L.jpg",
    url: "https://s.shopee.co.id/3B4xui67VY",
    featured: true,
  },
  {
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    category: "uang",
    hook: "Dua ayah, dua cara pandang soal uang. Yang kamu pilih menentukan sisa hidupmu.",
    cover: "https://covers.openlibrary.org/b/id/8315603-L.jpg",
    url: "https://s.shopee.co.id/30lXiP6kqX",
    featured: true,
  },
  {
    title: "Cashflow Quadrant",
    author: "Robert T. Kiyosaki",
    category: "uang",
    hook: "Pindah dari kuadran 'kerja demi uang' ke 'uang yang kerja untukmu'.",
    cover: "https://covers.openlibrary.org/b/id/496856-L.jpg",
    url: "https://s.shopee.co.id/2qS7W67OBW",
  },
  {
    title: "Manusia Terkaya di Babylon",
    author: "George S. Clason",
    category: "uang",
    hook: "Tujuh aturan kuno menumbuhkan kekayaan yang masih relevan 5.000 tahun kemudian.",
    cover: "https://covers.openlibrary.org/b/id/10491331-L.jpg",
    url: "https://s.shopee.co.id/2g8hJn81WV",
  },
  {
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    category: "uang",
    hook: "Buku kekayaan paling berpengaruh sepanjang masa — disarikan dari 500 orang terkaya.",
    cover: "https://covers.openlibrary.org/b/id/14542536-L.jpg",
    url: "https://s.shopee.co.id/3qKehw3a9k",
  },
  {
    title: "The Total Money Makeover",
    author: "Dave Ramsey",
    category: "uang",
    hook: "Lunasi utang, bangun dana darurat, berhenti hidup gali-tutup lubang.",
    cover: "https://covers.openlibrary.org/b/id/6873839-L.jpg",
    url: "https://s.shopee.co.id/3g1EVd4DUj",
  },
  {
    title: "The Millionaire Next Door",
    author: "Thomas J. Stanley",
    category: "uang",
    hook: "Jutawan sungguhan bukan yang pamer — riset siapa yang benar-benar kaya.",
    cover: "https://covers.openlibrary.org/b/id/797467-L.jpg",
    url: "https://s.shopee.co.id/3VhoJK4qpi",
  },
  {
    title: "I Will Teach You to Be Rich",
    author: "Ramit Sethi",
    category: "uang",
    hook: "Sistem keuangan otomatis 6 minggu — tanpa harus berhenti ngopi.",
    cover: "https://covers.openlibrary.org/b/id/6305971-L.jpg",
    url: "https://s.shopee.co.id/3LOO715UAh",
  },
  {
    title: "7 Keajaiban Rezeki",
    author: "Ippho Santosa",
    category: "uang",
    hook: "Strategi rezeki ala otak kanan — sedekah, ikhtiar, dan keberanian bermimpi besar.",
    cover: "https://covers.openlibrary.org/b/id/13767478-L.jpg",
    url: "https://s.shopee.co.id/4VaLVA12nw",
  },
  {
    title: "Mimpi Sejuta Dolar",
    author: "Merry Riana",
    category: "uang",
    hook: "Dari mahasiswa berutang jadi jutawan di usia 26 — kisah nyata yang membakar semangat.",
    cover: "https://down-id.img.susercontent.com/file/id-11134207-8224t-mimr4tnwy7t373.webp",
    url: "https://s.shopee.co.id/4LGvIr1g8v",
  },
  {
    title: "Money: Master the Game",
    author: "Tony Robbins",
    category: "uang",
    hook: "7 langkah menuju kebebasan finansial dari wawancara 50 investor legendaris dunia.",
    cover: "https://covers.openlibrary.org/b/id/8051347-L.jpg",
    url: "https://s.shopee.co.id/4AxV6Y2JTu",
  },
  {
    title: "Financial Freedom",
    author: "Grant Sabatier",
    category: "uang",
    hook: "Cetak biru pensiun dini — uang adalah waktu, dan kamu bisa membelinya kembali.",
    cover: "https://covers.openlibrary.org/b/id/8807095-L.jpg",
    url: "https://s.shopee.co.id/40e4uF2wot",
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    category: "kebiasaan",
    hook: "Perubahan 1% tiap hari yang menggandakan hidupmu dalam setahun.",
    cover: "https://covers.openlibrary.org/b/id/12539702-L.jpg",
    url: "https://s.shopee.co.id/3VhoJXMUZX",
    featured: true,
  },
  {
    title: "The Power of Habit",
    author: "Charles Duhigg",
    category: "kebiasaan",
    hook: "Bongkar 'loop' kebiasaan — pahami pemicunya, ubah hidupmu.",
    cover: "https://covers.openlibrary.org/b/id/9078085-L.jpg",
    url: "https://s.shopee.co.id/30lXicOOaS",
  },
  {
    title: "7 Kebiasaan Manusia yang Sangat Efektif",
    author: "Stephen R. Covey",
    category: "kebiasaan",
    hook: "Tujuh prinsip abadi yang membentuk pribadi paling produktif di dunia.",
    cover: "https://covers.openlibrary.org/b/id/10079937-L.jpg",
    url: "https://s.shopee.co.id/3B4xuvNlFV",
  },
  {
    title: "Deep Work",
    author: "Cal Newport",
    category: "kebiasaan",
    hook: "Fokus tanpa gangguan adalah skill terlangka — dan paling menghasilkan.",
    cover: "https://covers.openlibrary.org/b/id/7988607-L.jpg",
    url: "https://s.shopee.co.id/2g8hK0PfGQ",
  },
  {
    title: "Eat That Frog!",
    author: "Brian Tracy",
    category: "kebiasaan",
    hook: "Kerjakan tugas tersulit lebih dulu — sisa harimu jadi ringan.",
    cover: "https://covers.openlibrary.org/b/id/847534-L.jpg",
    url: "https://s.shopee.co.id/2qS7WJP1vT",
  },
  {
    title: "Essentialism",
    author: "Greg McKeown",
    category: "kebiasaan",
    hook: "Bukan melakukan lebih banyak — tapi melakukan yang benar-benar penting saja.",
    cover: "https://covers.openlibrary.org/b/id/7285986-L.jpg",
    url: "https://s.shopee.co.id/50Wc6IGmWu",
  },
  {
    title: "The 5 AM Club",
    author: "Robin Sharma",
    category: "kebiasaan",
    hook: "Cara satu jam pertama paginya mengubah seluruh sisa harimu.",
    cover: "https://covers.openlibrary.org/b/id/10326643-L.jpg",
    url: "https://s.shopee.co.id/5Aq2IbG9Bx",
  },
  {
    title: "The One Thing",
    author: "Gary Keller",
    category: "kebiasaan",
    hook: "Satu pertanyaan fokus yang membuat segalanya jadi lebih mudah atau tak perlu.",
    cover: "https://covers.openlibrary.org/b/id/10351762-L.jpg",
    url: "https://s.shopee.co.id/4ftlhgI3Cs",
  },
  {
    title: "Make Time",
    author: "Jake Knapp",
    category: "kebiasaan",
    hook: "Rebut kembali waktumu dari notifikasi dan rapat tak berujung.",
    cover: "https://covers.openlibrary.org/b/id/14179816-L.jpg",
    url: "https://s.shopee.co.id/4qDBtzHPrv",
  },
  {
    title: "The Compound Effect",
    author: "Darren Hardy",
    category: "kebiasaan",
    hook: "Pilihan kecil yang konsisten menumpuk jadi hasil yang luar biasa.",
    cover: "https://covers.openlibrary.org/b/id/7115046-L.jpg",
    url: "https://s.shopee.co.id/4LGvJ4JJsq",
  },
  {
    title: "The Slight Edge",
    author: "Jeff Olson",
    category: "kebiasaan",
    hook: "Kesuksesan adalah disiplin kecil yang diulang — sederhana, tapi jarang dilakukan.",
    cover: "https://covers.openlibrary.org/b/id/7285715-L.jpg",
    url: "https://s.shopee.co.id/4VaLVNIgXt",
  },
  {
    title: "Getting Things Done",
    author: "David Allen",
    category: "kebiasaan",
    hook: "Kosongkan kepalamu, taruh semua di sistem — pikiran jernih, kerja kelar.",
    cover: "https://covers.openlibrary.org/b/id/109288-L.jpg",
    url: "https://s.shopee.co.id/40e4uSKaYo",
  },
  {
    title: "Sebuah Seni untuk Bersikap Bodo Amat",
    author: "Mark Manson",
    category: "mindset",
    hook: "Berhenti peduli pada hal yang salah — fokuskan energi pada yang benar-benar penting.",
    cover: "https://covers.openlibrary.org/b/id/8231990-L.jpg",
    url: "https://s.shopee.co.id/60P9IXksDU",
    featured: true,
  },
  {
    title: "Segala-galanya Ambyar",
    author: "Mark Manson",
    category: "mindset",
    hook: "Di dunia penuh harapan palsu, harapan yang sehat justru menyelamatkan — sekuel berani 'Bodo Amat'.",
    cover: "https://covers.openlibrary.org/b/id/9351865-L.jpg",
    url: "https://s.shopee.co.id/6AiZUqkEsX",
  },
  {
    title: "Berani Tidak Disukai",
    author: "Ichiro Kishimi",
    category: "mindset",
    hook: "Kebebasan sejati adalah keberanian untuk tidak disukai semua orang.",
    cover: "https://covers.openlibrary.org/b/id/10873626-L.jpg",
    url: "https://s.shopee.co.id/6L1zh9jbXa",
  },
  {
    title: "Filosofi Teras",
    author: "Henry Manampiring",
    category: "mindset",
    hook: "Filsafat Stoa 2.000 tahun untuk mengelola cemas dan emosi orang Indonesia hari ini.",
    cover: "https://down-id.img.susercontent.com/file/id-11134207-7rase-m4c3q9z3x8qg25.webp",
    url: "https://s.shopee.co.id/6VLPtSiyCd",
  },
  {
    title: "Mindset",
    author: "Carol S. Dweck",
    category: "mindset",
    hook: "Percaya kemampuan bisa tumbuh — satu keyakinan yang mengubah segalanya.",
    cover: "https://covers.openlibrary.org/b/id/746414-L.jpg",
    url: "https://s.shopee.co.id/4AxV7ArqwC",
  },
  {
    title: "Grit",
    author: "Angela Duckworth",
    category: "mindset",
    hook: "Bukan bakat yang menentukan sukses, tapi ketekunan jangka panjang.",
    cover: "https://covers.openlibrary.org/b/id/7438753-L.jpg",
    url: "https://s.shopee.co.id/40e4ursUHB",
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    category: "mindset",
    hook: "Dua sistem di kepalamu — dan kenapa intuisi sering menipu.",
    cover: "https://covers.openlibrary.org/b/id/13290711-L.jpg",
    url: "https://s.shopee.co.id/4VaLVmqaGI",
  },
  {
    title: "Ikigai",
    author: "Héctor García",
    category: "mindset",
    hook: "Rahasia umur panjang dan bahagia orang Jepang: temukan alasanmu bangun pagi.",
    cover: "https://covers.openlibrary.org/b/id/11300391-L.jpg",
    url: "https://s.shopee.co.id/4LGvJTrDbH",
  },
  {
    title: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    category: "mindset",
    hook: "Dari neraka kamp konsentrasi: makna hidup bisa ditemukan di penderitaan terdalam.",
    cover: "https://covers.openlibrary.org/b/id/8516506-L.jpg",
    url: "https://s.shopee.co.id/4qDBuOpJaO",
  },
  {
    title: "The Power of Now",
    author: "Eckhart Tolle",
    category: "mindset",
    hook: "Penderitaanmu lahir dari masa lalu dan masa depan — kuncinya hidup di saat ini.",
    cover: "https://covers.openlibrary.org/b/id/551262-L.jpg",
    url: "https://s.shopee.co.id/4ftli5pwvN",
  },
  {
    title: "Emotional Intelligence",
    author: "Daniel Goleman",
    category: "mindset",
    hook: "IQ membuatmu diterima kerja, EQ yang membuatmu naik jabatan.",
    cover: "https://covers.openlibrary.org/b/id/1359485-L.jpg",
    url: "https://s.shopee.co.id/5Aq2J0o2uU",
  },
  {
    title: "Quiet",
    author: "Susan Cain",
    category: "mindset",
    hook: "Kekuatan introvert di dunia yang tak berhenti bicara.",
    cover: "https://covers.openlibrary.org/b/id/7079753-L.jpg",
    url: "https://s.shopee.co.id/50Wc6hogFT",
  },
  {
    title: "Influence",
    author: "Robert B. Cialdini",
    category: "mindset",
    hook: "Enam senjata psikologi yang membuat orang berkata 'ya' — pahami biar tak termanipulasi.",
    cover: "https://covers.openlibrary.org/b/id/431011-L.jpg",
    url: "https://s.shopee.co.id/2qS7Wiwve4",
  },
  {
    title: "12 Rules for Life",
    author: "Jordan B. Peterson",
    category: "mindset",
    hook: "Dua belas aturan menata kekacauan jadi hidup yang bermakna.",
    cover: "https://covers.openlibrary.org/b/id/8131760-L.jpg",
    url: "https://s.shopee.co.id/2g8hKPxYz3",
  },
  {
    title: "Loving the Wounded Soul",
    author: "Regis Machdy",
    category: "mindset",
    hook: "Memahami depresi dengan empati — dari seseorang yang pernah di dasar jurang.",
    cover: "https://down-id.img.susercontent.com/file/id-11134207-7rasj-m51pykrtnj9c77.webp",
    url: "https://s.shopee.co.id/3B4xvKveyA",
  },
  {
    title: "Insecurity is My Middle Name",
    author: "Alvi Syahrin",
    category: "mindset",
    hook: "Berdamai dengan rasa tak cukup — buku yang memeluk generasi cemas.",
    cover: "https://down-id.img.susercontent.com/file/id-11134207-822ws-moxlj7af2rr47b.webp",
    url: "https://s.shopee.co.id/30lXj1wIJ9",
  },
  {
    title: "Zero to One",
    author: "Peter Thiel",
    category: "bisnis",
    hook: "Membangun masa depan bukan meniru yang sudah ada — dari nol jadi satu.",
    cover: "https://covers.openlibrary.org/b/id/9002334-L.jpg",
    url: "https://s.shopee.co.id/7pqnUBMzRl",
    featured: true,
  },
  {
    title: "The Lean Startup",
    author: "Eric Ries",
    category: "bisnis",
    hook: "Bangun, ukur, belajar — cara memulai bisnis tanpa membakar uang sia-sia.",
    cover: "https://covers.openlibrary.org/b/id/7104760-L.jpg",
    url: "https://s.shopee.co.id/7KuWtGOtSg",
  },
  {
    title: "Good to Great",
    author: "Jim Collins",
    category: "bisnis",
    hook: "Apa yang membuat perusahaan biasa melompat jadi luar biasa — hasil riset 5 tahun.",
    cover: "https://covers.openlibrary.org/b/id/10866207-L.jpg",
    url: "https://s.shopee.co.id/7VDx5ZOG7j",
  },
  {
    title: "Start with Why",
    author: "Simon Sinek",
    category: "bisnis",
    hook: "Orang tidak beli apa yang kamu jual, tapi kenapa kamu menjualnya.",
    cover: "https://covers.openlibrary.org/b/id/6395237-L.jpg",
    url: "https://s.shopee.co.id/8Kn456L5Qu",
  },
  {
    title: "Shoe Dog",
    author: "Phil Knight",
    category: "bisnis",
    hook: "Kisah jujur dan berdarah-darah di balik lahirnya Nike.",
    cover: "https://covers.openlibrary.org/b/id/8858487-L.jpg",
    url: "https://s.shopee.co.id/8V6UHPKS5x",
  },
  {
    title: "The $100 Startup",
    author: "Chris Guillebeau",
    category: "bisnis",
    hook: "Mulai bisnis untung dari modal kecil — puluhan kisah nyata jadi buktinya.",
    cover: "https://covers.openlibrary.org/b/id/7257004-L.jpg",
    url: "https://s.shopee.co.id/80ADgUMM6s",
  },
  {
    title: "Rework",
    author: "Jason Fried",
    category: "bisnis",
    hook: "Lupakan rencana bisnis tebal — cara kerja yang lebih nyata dan jujur.",
    cover: "https://covers.openlibrary.org/b/id/6679955-L.jpg",
    url: "https://s.shopee.co.id/8ATdsnLilv",
  },
  {
    title: "The E-Myth Revisited",
    author: "Michael E. Gerber",
    category: "bisnis",
    hook: "Kenapa kebanyakan usaha kecil gagal — dan cara bangun bisnis yang jalan tanpamu.",
    cover: "https://covers.openlibrary.org/b/id/684209-L.jpg",
    url: "https://s.shopee.co.id/902ksKIY56",
  },
  {
    title: "Blue Ocean Strategy",
    author: "W. Chan Kim",
    category: "bisnis",
    hook: "Berhenti berdarah-darah di pasar penuh pesaing — ciptakan pasar baru tanpa lawan.",
    cover: "https://covers.openlibrary.org/b/id/8219313-L.jpg",
    url: "https://s.shopee.co.id/9AMB4dHuk9",
  },
  {
    title: "Business Model Generation",
    author: "Alexander Osterwalder",
    category: "bisnis",
    hook: "Rancang model bisnis di satu kanvas — visual, cepat, dipakai jutaan startup.",
    cover: "https://covers.openlibrary.org/b/id/6675500-L.jpg",
    url: "https://s.shopee.co.id/8fPuTiJol4",
  },
  {
    title: "The 4-Hour Workweek",
    author: "Timothy Ferriss",
    category: "bisnis",
    hook: "Lepas dari jebakan kerja 9-ke-5 — desain hidup dan bisnis yang otomatis.",
    cover: "https://covers.openlibrary.org/b/id/539652-L.jpg",
    url: "https://s.shopee.co.id/8pjKg1JBQ7",
  },
  {
    title: "The Hard Thing About Hard Things",
    author: "Ben Horowitz",
    category: "bisnis",
    hook: "Tak ada resep untuk keputusan tersulit — nasihat jujur dari ruang CEO.",
    cover: "https://covers.openlibrary.org/b/id/7279515-L.jpg",
    url: "https://s.shopee.co.id/9fIRfYG0jI",
  },
  {
    title: "Crushing It!",
    author: "Gary Vaynerchuk",
    category: "bisnis",
    hook: "Bangun personal brand dan ubah passion jadi penghasilan di era media sosial.",
    cover: "https://covers.openlibrary.org/b/id/6297122-L.jpg",
    url: "https://s.shopee.co.id/9pbrrrFNOL",
  },
  {
    title: "The Innovator's Dilemma",
    author: "Clayton M. Christensen",
    category: "bisnis",
    hook: "Kenapa perusahaan hebat justru kalah oleh pemain kecil yang mengganggu.",
    cover: "https://covers.openlibrary.org/b/id/9274687-L.jpg",
    url: "https://s.shopee.co.id/9KfbGwHHPG",
  },
  {
    title: "Built to Last",
    author: "Jim Collins",
    category: "bisnis",
    hook: "Apa yang membuat perusahaan bertahan visioner selama puluhan tahun.",
    cover: "https://covers.openlibrary.org/b/id/684195-L.jpg",
    url: "https://s.shopee.co.id/9Uz1TFGe4J",
  },
  {
    title: "Marketing 5.0",
    author: "Philip Kotler",
    category: "bisnis",
    hook: "Teknologi bertemu sentuhan manusia — pemasaran di era AI dari bapak marketing.",
    cover: "https://covers.openlibrary.org/b/id/14012087-L.jpg",
    url: "https://s.shopee.co.id/AKY8SmDTNU",
  },
  {
    title: "Leaders Eat Last",
    author: "Simon Sinek",
    category: "kepemimpinan",
    hook: "Pemimpin sejati makan terakhir — bangun tim yang saling melindungi.",
    cover: "https://covers.openlibrary.org/b/id/8246311-L.jpg",
    url: "https://s.shopee.co.id/AAEiGiuvUM",
  },
  {
    title: "Bagaimana Mencari Kawan & Memengaruhi Orang",
    author: "Dale Carnegie",
    category: "kepemimpinan",
    hook: "Buku relasi manusia terlaris sepanjang masa — masih ampuh setelah 85 tahun.",
    cover: "https://covers.openlibrary.org/b/id/13314878-L.jpg",
    url: "https://s.shopee.co.id/9zvI4PvYpL",
  },
  {
    title: "21 Hukum Kepemimpinan Sejati",
    author: "John C. Maxwell",
    category: "kepemimpinan",
    hook: "Dua puluh satu hukum kepemimpinan yang bisa dipelajari siapa saja.",
    cover: "https://covers.openlibrary.org/b/id/1465659-L.jpg",
    url: "https://s.shopee.co.id/LkmYeWMRU",
  },
  {
    title: "Drive",
    author: "Daniel H. Pink",
    category: "kepemimpinan",
    hook: "Rahasia motivasi sejati bukan uang — tapi otonomi, penguasaan, dan tujuan.",
    cover: "https://covers.openlibrary.org/b/id/6404786-L.jpg",
    url: "https://s.shopee.co.id/W4CkxVj6X",
  },
  {
    title: "Dare to Lead",
    author: "Brené Brown",
    category: "kepemimpinan",
    hook: "Memimpin dengan keberanian dan kerentanan — bukan dengan kuasa dan ketakutan.",
    cover: "https://covers.openlibrary.org/b/id/7367250-L.jpg",
    url: "https://s.shopee.co.id/17wA2Xd7S",
  },
  {
    title: "Extreme Ownership",
    author: "Jocko Willink",
    category: "kepemimpinan",
    hook: "Pelajaran kepemimpinan Navy SEAL: pemimpin bertanggung jawab atas segalanya.",
    cover: "https://covers.openlibrary.org/b/id/12835042-L.jpg",
    url: "https://s.shopee.co.id/BRMMLWzmV",
  },
  {
    title: "The Five Dysfunctions of a Team",
    author: "Patrick Lencioni",
    category: "kepemimpinan",
    hook: "Lima jebakan yang menghancurkan tim — dan cara membangun kepercayaan.",
    cover: "https://covers.openlibrary.org/b/id/10863273-L.jpg",
    url: "https://s.shopee.co.id/110TLsTp5g",
  },
  {
    title: "Multipliers",
    author: "Liz Wiseman",
    category: "kepemimpinan",
    hook: "Pemimpin hebat membuat semua orang di sekitarnya jadi lebih pintar.",
    cover: "https://covers.openlibrary.org/b/id/9265081-L.jpg",
    url: "https://s.shopee.co.id/1BJtYBTBkj",
  },
  {
    title: "Radical Candor",
    author: "Kim Scott",
    category: "kepemimpinan",
    hook: "Peduli secara tulus sekaligus berani menantang langsung — seni memberi feedback.",
    cover: "https://covers.openlibrary.org/b/id/8088432-L.jpg",
    url: "https://s.shopee.co.id/gNcxGV5le",
  },
  {
    title: "Measure What Matters",
    author: "John Doerr",
    category: "kepemimpinan",
    hook: "OKR — sistem target yang membuat Google dan Intel meledak pertumbuhannya.",
    cover: "https://covers.openlibrary.org/b/id/10706481-L.jpg",
    url: "https://s.shopee.co.id/qh39ZUSQh",
  },
  {
    title: "The Infinite Game",
    author: "Simon Sinek",
    category: "kepemimpinan",
    hook: "Bisnis bukan soal menang — tapi soal bertahan dan berkembang selamanya.",
    cover: "https://covers.openlibrary.org/b/id/10189716-L.jpg",
    url: "https://s.shopee.co.id/1gGA96RHjs",
  },
  {
    title: "Berpikir dan Berjiwa Besar",
    author: "David J. Schwartz",
    category: "kepemimpinan",
    hook: "Ukuran kesuksesanmu ditentukan oleh ukuran cara berpikirmu.",
    cover: "https://covers.openlibrary.org/b/id/480539-L.jpg",
    url: "https://s.shopee.co.id/1qZaLPQeOv",
  },
  {
    title: "This Is Marketing",
    author: "Seth Godin",
    category: "marketing",
    hook: "Pemasaran bukan soal teriak ke semua orang — tapi melayani sekelompok yang tepat.",
    cover: "https://covers.openlibrary.org/b/id/14624926-L.jpg",
    url: "https://s.shopee.co.id/7KuWtkudPQ",
  },
  {
    title: "Contagious",
    author: "Jonah Berger",
    category: "marketing",
    hook: "Kenapa sebagian hal jadi viral — enam prinsip di balik kata dari mulut ke mulut.",
    cover: "https://covers.openlibrary.org/b/id/9039370-L.jpg",
    url: "https://s.shopee.co.id/7VDx63u04T",
  },
  {
    title: "Made to Stick",
    author: "Chip Heath",
    category: "marketing",
    hook: "Kenapa ide tertentu melekat di kepala — dan cara membuat pesanmu tak terlupakan.",
    cover: "https://covers.openlibrary.org/b/id/7004880-L.jpg",
    url: "https://s.shopee.co.id/7fXNIMtMjW",
  },
  {
    title: "Building a StoryBrand",
    author: "Donald Miller",
    category: "marketing",
    hook: "Jadikan pelanggan pahlawannya, brand-mu pemandunya — pesan yang langsung nyambung.",
    cover: "https://covers.openlibrary.org/b/id/8458703-L.jpg",
    url: "https://s.shopee.co.id/7pqnUfsjOZ",
  },
  {
    title: "Hooked",
    author: "Nir Eyal",
    category: "marketing",
    hook: "Cara produk membentuk kebiasaan yang membuat orang kembali lagi dan lagi.",
    cover: "https://covers.openlibrary.org/b/id/12511799-L.jpg",
    url: "https://s.shopee.co.id/5L9SW52FT6",
  },
  {
    title: "$100M Offers",
    author: "Alex Hormozi",
    category: "marketing",
    hook: "Bikin penawaran yang terlalu bagus untuk ditolak — sampai orang merasa bodoh kalau menolak.",
    cover: "https://down-id.img.susercontent.com/file/id-11134207-8224r-miv9krpbzoxx2f.webp",
    url: "https://s.shopee.co.id/5VSsiO1c89",
  },
  {
    title: "Jab, Jab, Jab, Right Hook",
    author: "Gary Vaynerchuk",
    category: "marketing",
    hook: "Beri nilai dulu, baru jualan — ritme konten media sosial yang benar.",
    cover: "https://covers.openlibrary.org/b/id/11955993-L.jpg",
    url: "https://s.shopee.co.id/5fmIuh0ynC",
  },
  {
    title: "Purple Cow",
    author: "Seth Godin",
    category: "marketing",
    hook: "Di pasar penuh sapi cokelat, jadilah sapi ungu — kalau tak luar biasa, kamu tak terlihat.",
    cover: "https://covers.openlibrary.org/b/id/866008-L.jpg",
    url: "https://s.shopee.co.id/5q5j700LSF",
  },
  {
    title: "Positioning",
    author: "Al Ries",
    category: "marketing",
    hook: "Pertarungan pemasaran terjadi di benak konsumen — rebut posisinya lebih dulu.",
    cover: "https://covers.openlibrary.org/b/id/55745-L.jpg",
    url: "https://s.shopee.co.id/60P9JIzi7I",
  },
  {
    title: "Permission Marketing",
    author: "Seth Godin",
    category: "marketing",
    hook: "Berhenti mengganggu — dapatkan izin pelanggan untuk dipasarkan.",
    cover: "https://covers.openlibrary.org/b/id/427916-L.jpg",
    url: "https://s.shopee.co.id/6AiZVbz4mL",
  },
  {
    title: "Influence: Science and Practice",
    author: "Robert B. Cialdini",
    category: "marketing",
    hook: "Edisi sains-dan-praktik: bedah riset di balik tiap teknik persuasi yang menggerakkan keputusan beli.",
    cover: "https://covers.openlibrary.org/b/id/431011-L.jpg",
    url: "https://s.shopee.co.id/6L1zhuyRRO",
  },
  {
    title: "Oversubscribed",
    author: "Daniel Priestley",
    category: "marketing",
    hook: "Buat permintaan melebihi pasokan — sampai orang antre membeli darimu.",
    cover: "https://covers.openlibrary.org/b/id/13784244-L.jpg",
    url: "https://s.shopee.co.id/6VLPuDxo6R",
  },
  {
    title: "Never Split the Difference",
    author: "Chris Voss",
    category: "komunikasi",
    hook: "Teknik negosiasi mantan negosiator sandera FBI — menang tanpa berkompromi.",
    cover: "https://covers.openlibrary.org/b/id/8365942-L.jpg",
    url: "https://s.shopee.co.id/1qZaLqcUyH",
  },
  {
    title: "Crucial Conversations",
    author: "Kerry Patterson",
    category: "komunikasi",
    hook: "Cara bicara saat taruhannya tinggi dan emosi memuncak — tanpa merusak hubungan.",
    cover: "https://covers.openlibrary.org/b/id/1711809-L.jpg",
    url: "https://s.shopee.co.id/1gGA9Xd8JE",
  },
  {
    title: "Talk Like TED",
    author: "Carmine Gallo",
    category: "komunikasi",
    hook: "Sembilan rahasia presentasi paling memukau dari panggung TED.",
    cover: "https://covers.openlibrary.org/b/id/7316010-L.jpg",
    url: "https://s.shopee.co.id/1LdJkveOzC",
  },
  {
    title: "Surrounded by Idiots",
    author: "Thomas Erikson",
    category: "komunikasi",
    hook: "Empat tipe kepribadian warna — pahami kenapa orang lain bikin frustrasi.",
    cover: "https://covers.openlibrary.org/b/id/10105591-L.jpg",
    url: "https://s.shopee.co.id/1VwjxEdleF",
  },
  {
    title: "How to Talk to Anyone",
    author: "Leil Lowndes",
    category: "komunikasi",
    hook: "92 trik kecil untuk percaya diri dan disukai di setiap percakapan.",
    cover: "https://covers.openlibrary.org/b/id/58950-L.jpg",
    url: "https://s.shopee.co.id/2LVqwlaaxQ",
  },
  {
    title: "5 Bahasa Kasih",
    author: "Gary Chapman",
    category: "komunikasi",
    hook: "Lima cara mengungkap dan menerima cinta — kunci hubungan yang awet.",
    cover: "https://covers.openlibrary.org/b/id/12602983-L.jpg",
    url: "https://s.shopee.co.id/2VpH94ZxcT",
  },
  {
    title: "Komunikasi Tanpa Kekerasan",
    author: "Marshall B. Rosenberg",
    category: "komunikasi",
    hook: "Bicara dari hati ke hati — selesaikan konflik tanpa menyakiti.",
    cover: "https://covers.openlibrary.org/b/id/940686-L.jpg",
    url: "https://s.shopee.co.id/20t0Y9brdO",
  },
  {
    title: "The Charisma Myth",
    author: "Olivia Fox Cabane",
    category: "komunikasi",
    hook: "Karisma bukan bawaan lahir — ia keterampilan yang bisa dilatih.",
    cover: "https://covers.openlibrary.org/b/id/13882953-L.jpg",
    url: "https://s.shopee.co.id/2BCQkSbEIR",
  },
  {
    title: "Daring Greatly",
    author: "Brené Brown",
    category: "komunikasi",
    hook: "Keberanian untuk terlihat rentan adalah ukuran sejati kekuatan.",
    cover: "https://covers.openlibrary.org/b/id/7367250-L.jpg",
    url: "https://s.shopee.co.id/LkmZ5iD16",
  },
  {
    title: "Verbal Judo",
    author: "George J. Thompson",
    category: "komunikasi",
    hook: "Seni meredam konflik dengan kata-kata — ubah perlawanan jadi kerja sama.",
    cover: "https://covers.openlibrary.org/b/id/3932405-L.jpg",
    url: "https://s.shopee.co.id/W4ClOhZg9",
  },
  {
    title: "Can't Hurt Me",
    author: "David Goggins",
    category: "wawasan",
    hook: "Dari obesitas dan trauma jadi manusia terkuat — kuasai pikiranmu sendiri.",
    cover: "https://covers.openlibrary.org/b/id/8305903-L.jpg",
    url: "https://s.shopee.co.id/1gGA9i2NZS",
  },
  {
    title: "Sang Alkemis",
    author: "Paulo Coelho",
    category: "wawasan",
    hook: "Kisah gembala mencari harta — dan menemukan makna takdir di sepanjang jalan.",
    cover: "https://covers.openlibrary.org/b/id/7414780-L.jpg",
    url: "https://s.shopee.co.id/1qZaM11kEV",
  },
  {
    title: "Sapiens",
    author: "Yuval Noah Harari",
    category: "wawasan",
    hook: "Bagaimana spesies biasa menguasai dunia — sejarah singkat umat manusia.",
    cover: "https://covers.openlibrary.org/b/id/8634250-L.jpg",
    url: "https://s.shopee.co.id/20t0YK16tY",
    featured: true,
  },
  {
    title: "Homo Deus",
    author: "Yuval Noah Harari",
    category: "wawasan",
    hook: "Setelah menaklukkan kelaparan dan wabah, manusia mengejar keabadian — masa depan kita.",
    cover: "https://covers.openlibrary.org/b/id/7914168-L.jpg",
    url: "https://s.shopee.co.id/2BCQkd0TYb",
  },
  {
    title: "Outliers",
    author: "Malcolm Gladwell",
    category: "wawasan",
    hook: "Rahasia orang-orang sukses luar biasa — bukan cuma bakat, tapi kesempatan dan 10.000 jam.",
    cover: "https://covers.openlibrary.org/b/id/10021591-L.jpg",
    url: "https://s.shopee.co.id/2LVqwvzqDe",
  },
  {
    title: "Blink",
    author: "Malcolm Gladwell",
    category: "wawasan",
    hook: "Kekuatan berpikir tanpa berpikir — keputusan dalam sekejap yang ternyata akurat.",
    cover: "https://covers.openlibrary.org/b/id/14421850-L.jpg",
    url: "https://s.shopee.co.id/2VpH9EzCsh",
  },
  {
    title: "Originals",
    author: "Adam Grant",
    category: "wawasan",
    hook: "Bagaimana para pembangkang menggerakkan dunia dengan ide yang berani beda.",
    cover: "https://covers.openlibrary.org/b/id/8870353-L.jpg",
    url: "https://s.shopee.co.id/17wAe8ixE",
  },
  {
    title: "Give and Take",
    author: "Adam Grant",
    category: "wawasan",
    hook: "Kenapa para pemberi justru paling sukses dalam jangka panjang.",
    cover: "https://covers.openlibrary.org/b/id/7391212-L.jpg",
    url: "https://s.shopee.co.id/BRMMx85cH",
  },
  {
    title: "Show Your Work!",
    author: "Austin Kleon",
    category: "wawasan",
    hook: "Berhenti bersembunyi — bagikan prosesmu dan biarkan dunia menemukanmu.",
    cover: "https://covers.openlibrary.org/b/id/7284188-L.jpg",
    url: "https://s.shopee.co.id/LkmZG7SHK",
  },
  {
    title: "Steal Like an Artist",
    author: "Austin Kleon",
    category: "wawasan",
    hook: "Tak ada yang benar-benar orisinal — kreativitas adalah seni mencuri dengan cerdas.",
    cover: "https://covers.openlibrary.org/b/id/7244512-L.jpg",
    url: "https://s.shopee.co.id/W4ClZ6owN",
  },
];
