import Image from "next/image";
import Link from "next/link";
import {
  ArrowRight,
  Check,
  X,
  Download,
  Lock,
  Infinity as InfinityIcon,
  LayoutTemplate,
  Captions,
  Crop,
  MoonStar,
  Server,
  KeyRound,
  Palette,
  ChevronRight,
  ChevronDown,
} from "lucide-react";
import { buildMeta } from "@/lib/metadata";
import { AnimatedSection } from "@/components/shared/AnimatedSection";
import { CONTACT } from "@/lib/constants";
import { CheckoutForm } from "./CheckoutForm";
import { Stepper } from "./Stepper";

const PRICE = "Rp 90.467";

export const metadata = buildMeta({
  title: "Clipper by Mote — Bikin Klip Pendek dari YouTube, Sekali Bayar",
  description:
    "Paste link YouTube, AI pilih momen terbaik, jadi klip vertikal ber-caption — semua jalan di komputer kamu sendiri. 4 paket gaya, 8 gaya caption, 3 mode framing. Bayar sekali " +
    PRICE +
    ", punya selamanya. Tanpa langganan bulanan.",
  path: "/products/clipper",
});

const FEATURES = [
  { icon: Lock, title: "100% lokal & privat", body: "Jalan di komputer kamu sendiri. Video gak pernah diupload ke server siapa pun." },
  { icon: InfinityIcon, title: "Tanpa batas render", body: "Bikin sebanyak yang kamu mau. Gak ada kuota menit, gak ada biaya per klip." },
  { icon: LayoutTemplate, title: "Empat paket gaya siap pakai", body: "Klik satu kartu, semua ikut: caption, framing, durasi klip, sampai brief buat AI-nya." },
  { icon: Captions, title: "Delapan gaya caption", body: "Karaoke, sticker kuning, reveal halus, dan lainnya. Font Anton sama Montserrat ikut dibundel, bukan nebeng font bawaan sistem." },
  { icon: Crop, title: "Tiga cara ngepasin frame", body: "Kamera ngikutin wajah, bar diblur, atau bar hitam polos. Yang tanpa face tracking jauh lebih ringan buat laptop." },
  { icon: MoonStar, title: "Tema terang & gelap", body: "Ikut setelan sistem, atau kunci ke salah satu. Buat yang ngedit sampai tengah malam." },
  { icon: KeyRound, title: "Cukup 2 API key gratis", body: "Gemini (Google AI Studio) + Groq. Dua-duanya punya paket gratis. Panduan ada di wizard." },
  { icon: Palette, title: "Brand kamu sendiri", body: "Set nama, logo, dan warna sendiri. Cocok buat agency yang mau tool ber-brand untuk klien." },
  { icon: Server, title: "Sekali install, punya selamanya", body: "docker compose up, isi 2 key, selesai. Gak ada langganan, gak ada yang bisa dimatikan." },
];

/**
 * Style bundles + caption styles.
 *
 * The thumbnails under /img/clipper/styles/ are REAL frames rendered by the
 * app's own pipeline (copied from apps/web/public/styles in clipper-rumahan,
 * generated by apps/worker/scripts/gen_style_previews.py). They are not
 * mockups, and that is the whole point of this section: the product is sold on
 * output quality, so the page has to show output, not a diagram of it.
 *
 * If the presets ever change, re-run that script and re-copy the webp files.
 * Labels here MUST match the labels inside the app, otherwise a buyer picks
 * "Punchy clips" on the page and can't find it on their own screen.
 */
const STYLE_BUNDLES = [
  {
    id: "viral",
    label: "Punchy clips",
    body: "Huruf kapital, kata yang lagi diucapin nyala satu per satu. Buat TikTok sama Reels.",
    speed: "Paling lama, pakai deteksi wajah",
  },
  {
    id: "podcast",
    label: "Full story",
    body: "Caption kalem, kata yang belum diucapin diredupin. Podcast, wawancara, obrolan panjang.",
    speed: "Paling lama, pakai deteksi wajah",
  },
  {
    id: "edu",
    label: "Screen & slides",
    body: "Gambarnya gak dipotong sama sekali, caption polos biar layarnya gak ketutup. Buat tutorial dan rekaman layar.",
    speed: "Paling cepat",
  },
  {
    id: "fast",
    label: "Fast & punchy",
    body: "Caption sama persis kayak Punchy, bedanya gambar gak dipotong dan bar atas bawahnya diblur. Pilihan aman buat laptop yang gak terlalu kuat.",
    speed: "Jauh lebih cepat, tanpa deteksi wajah",
  },
];

// The swatch is the description. A line of prose under each one would only
// restate what the reader can already see.
const CAPTION_STYLES = [
  { id: "popline", label: "Karaoke Punchy" },
  { id: "clean-bold", label: "Clean Bold" },
  { id: "reveal", label: "Soft Reveal" },
  { id: "sticker", label: "Yellow Sticker" },
  { id: "minimal", label: "Minimal" },
  { id: "brand", label: "Brand" },
];

const SUBSCRIPTION_CONS = [
  "Bayar tiap bulan, terus-terusan",
  "Render dibatasi kredit menit",
  "Video kamu diproses di server mereka",
  "Fitur bisa berubah atau ditarik sepihak",
  "Pakai brand mereka, bukan kamu",
  "Stop bayar = tool langsung mati",
];

const CLIPPER_PROS = [
  "Bayar sekali Rp 90.467, punya selamanya",
  "Render tanpa batas, sepuasnya",
  "100% lokal — video tetap di komputer kamu",
  "4 paket gaya + 8 gaya caption, bisa ganti per klip",
  "Brand kamu sendiri (nama, logo, warna)",
  "Tetap jalan selamanya, gak bisa dimatikan",
];

type Faq = {
  q: string;
  a: string;
  more?: { href: string; label: string };
};

const FAQS: Faq[] = [
  {
    q: "Bedanya sama Opus Clip apa?",
    a: "Opus Clip langganan bulanan dan video kamu diproses di server mereka. Clipper bayar sekali, jalan di komputer kamu sendiri, dan render-nya tanpa batas. Kamu pegang penuh.",
  },
  {
    q: "Gaya caption sama framing-nya bisa diganti?",
    a: "Bisa. Ada 4 paket siap pakai yang ngatur semuanya sekaligus, 8 gaya caption, dan 3 cara ngepasin frame (kamera ngikutin wajah, bar diblur, atau bar hitam polos). Kamu bisa nimpa gaya caption dan framing per klip tanpa ngubah setelan default kamu. Semua kartu preview di aplikasinya itu hasil render beneran, jadi yang kamu lihat sebelum klik sama dengan yang keluar.",
  },
  {
    q: "Render-nya lama gak?",
    a: "Tergantung mode framing yang kamu pilih dan seberapa kuat komputernya. Mode yang ngikutin wajah paling berat karena ada deteksi pembicara; mode bar diblur dan bar hitam jauh lebih ringan, di mesin ukur kami sekitar 7x lebih cepat. Kalau laptop kamu pas-pasan, pakai paket Fast & punchy atau Screen & slides. Estimasi waktunya juga tampil di aplikasi dan ikut berubah tiap kamu ganti gaya.",
  },
  {
    q: "Susah gak install-nya?",
    a: "Install Docker Desktop sekali, lalu double-click launcher (Mac/Windows). Wizard pertama nuntun kamu isi lisensi, brand, dan 2 API key gratis. Sekitar 10 menit — panduan lengkap ada di halaman setup.",
  },
  {
    q: "API key-nya bayar?",
    a: "Gratis. Gemini dari Google AI Studio dan Groq dua-duanya punya free tier yang cukup buat pemakaian normal. Link-nya disediakan di wizard.",
  },
  {
    q: "Lisensinya buat berapa perangkat?",
    a: "Lisensi terkunci ke satu perangkat (device-lock). Butuh pindah komputer atau lisensi tambahan? Chat WhatsApp kami.",
  },
  {
    q: "Ada refund?",
    a: "Kunci lisensi dikirim otomatis begitu pembayaran terverifikasi, jadi pembelian bersifat non-refundable setelah kunci diterbitkan. Pengecualiannya: kunci tidak sampai dalam 1×24 jam dan kami gagal menerbitkan ulang, atau aplikasi tidak bisa jalan di komputer kamu yang sudah memenuhi syarat sistem setelah didampingi tim kami. Ragu cocok atau tidak? Chat dulu via WhatsApp sebelum beli — kami jujur bilang cocok atau tidak.",
    more: { href: "/refund-policy", label: "Baca Kebijakan Refund selengkapnya" },
  },
];

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: FAQS.map(({ q, a }) => ({
    "@type": "Question",
    name: q,
    acceptedAnswer: { "@type": "Answer", text: a },
  })),
};

export default function ClipperPage() {
  return (
    <>
      {/* Announcement strip */}
      <div className="bg-[#06243B] text-white">
        <div className="container-mote flex items-center justify-center gap-2.5 py-2.5 text-center text-[13px] sm:text-sm">
          <span className="h-1.5 w-1.5 rounded-full bg-[#BDF24A] shrink-0" />
          <span className="text-white/85">
            Sekali bayar <b className="text-[#BDF24A]">{PRICE}</b> — punya selamanya. Tanpa langganan bulanan.
          </span>
        </div>
      </div>

      {/* Hero — centered */}
      <section className="bg-white pt-14 sm:pt-20 pb-10">
        <div className="container-mote">
          <AnimatedSection className="mx-auto max-w-3xl flex flex-col items-center text-center gap-6">
            <span className="eyebrow">AI Clipper Desktop · Lokal</span>
            <h1 className="text-[#06243B] text-balance">
              Bikin klip pendek dari YouTube — <span className="highlight-text">di laptop kamu sendiri.</span>
            </h1>
            <p className="text-[#3D4F60] text-lg leading-relaxed max-w-2xl">
              Paste link, AI pilih momen terbaik, jadi klip vertikal ber-caption. Semua diproses lokal —
              tanpa upload, tanpa watermark, tanpa langganan.
            </p>
            <div className="flex flex-col sm:flex-row items-center gap-3 w-full sm:w-auto pt-1">
              <a href="#beli" className="btn btn-dark group w-full sm:w-auto">
                Beli sekarang — {PRICE}
                <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
              </a>
              <a href="#gaya" className="btn btn-ghost w-full sm:w-auto">
                Lihat contoh hasilnya
              </a>
            </div>
          </AnimatedSection>

          {/* Product screenshot — the star */}
          <AnimatedSection className="mx-auto max-w-5xl mt-12 sm:mt-16">
            <div className="rounded-2xl overflow-hidden border border-black/10 bg-white shadow-[0_40px_100px_-40px_rgba(6,36,59,0.5)]">
              <div className="flex items-center gap-1.5 px-4 py-3 border-b border-black/5">
                <span className="h-2.5 w-2.5 rounded-full bg-[#06243B]/15" />
                <span className="h-2.5 w-2.5 rounded-full bg-[#06243B]/15" />
                <span className="h-2.5 w-2.5 rounded-full bg-[#06243B]/15" />
                <span className="ml-2 font-mono text-[11px] text-[#06243B]/45 truncate">
                  localhost:3060 — dashboard kamu, jalan lokal
                </span>
              </div>
              <Image
                src="/img/clipper-dashboard-v040.webp"
                alt="Dashboard Clipper: paste link YouTube, pilih paket gaya dari kartu preview, lalu generate klip pendek otomatis"
                width={1400}
                height={860}
                className="w-full h-auto"
                priority
                unoptimized
              />
            </div>
            <p className="text-center text-sm text-[#3D4F60]/70 mt-4">
              Tampilan asli aplikasinya. Kartu gaya di layar itu preview render beneran, bukan gambar
              contoh. Nama, logo, dan warnanya bisa kamu ganti jadi brand sendiri.
            </p>
          </AnimatedSection>
        </div>
      </section>

      {/* How it works — interactive stepper */}
      <section id="cara-kerja" className="bg-[#F7F8FA] py-20 sm:py-24 border-y border-black/5">
        <div className="container-mote flex flex-col gap-12">
          <AnimatedSection className="mx-auto max-w-2xl text-center flex flex-col items-center gap-3">
            <span className="eyebrow">Cara kerja</span>
            <h2 className="text-[#06243B]">Dari link jadi klip siap posting.</h2>
            <p className="text-[#3D4F60] leading-relaxed">
              Empat langkah, dan semuanya jalan di komputer kamu.
            </p>
          </AnimatedSection>
          <AnimatedSection>
            <Stepper />
          </AnimatedSection>
        </div>
      </section>

      {/* Sample output — real clip */}
      <section className="bg-white py-20 sm:py-24">
        <div className="container-mote grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16 items-center">
          <AnimatedSection className="order-1 lg:order-1 flex justify-center">
            <div className="w-[240px] sm:w-[280px] shrink-0 overflow-hidden rounded-[1.75rem] border border-black/10 bg-[#06243B]">
              <video
                src="/video/clipper-sample.mp4"
                poster="/video/clipper-sample-poster.jpg"
                className="block w-full aspect-[9/16] object-cover"
                playsInline
                controls
                preload="metadata"
              />
            </div>
          </AnimatedSection>
          <AnimatedSection className="order-2 lg:order-2 flex flex-col gap-4">
            <span className="eyebrow">Contoh hasil</span>
            <h2 className="text-[#06243B]">Contoh klip yang dihasilkan.</h2>
            <p className="text-[#3D4F60] leading-relaxed text-lg">
              Output asli Clipper — vertikal 9:16, caption otomatis, siap posting ke TikTok,
              Reels, atau Shorts.
            </p>
          </AnimatedSection>
        </div>
      </section>

      {/*
        Style bundles + caption styles.

        Light section on the page's own alternating rhythm, not an inverted
        navy block: the rest of this page is one continuous light theme and a
        dark band here reads as a different website mid-scroll.

        The thumbnails carry this section, so they get no card, no pill, and no
        second headline competing with them. Everything that isn't the image is
        a label.
      */}
      <section
        id="gaya"
        className="bg-[#F7F8FA] py-20 sm:py-24 border-y border-black/5 scroll-mt-24"
      >
        <div className="container-mote flex flex-col gap-12">
          <AnimatedSection className="mx-auto max-w-2xl text-center flex flex-col items-center gap-3">
            <span className="eyebrow">Pilihan gaya</span>
            <h2 className="text-[#06243B] max-sm:text-[1.375rem]">Gayanya kamu yang pilih.</h2>
            <p className="text-[#3D4F60] leading-relaxed">
              Empat paket siap pakai. Klik satu, caption sama framing-nya ngikut. Semua gambar di
              bawah ini frame asli hasil render aplikasinya, bukan ilustrasi.
            </p>
          </AnimatedSection>

          <div className="grid grid-cols-2 lg:grid-cols-4 gap-5 sm:gap-6">
            {STYLE_BUNDLES.map((s) => (
              <AnimatedSection key={s.id} className="flex h-full flex-col gap-3">
                {/* shrink-0 is load-bearing: this is a flex column whose other
                    child grows, and without it the 9:16 box gets compressed to
                    whatever height is left over. */}
                <div
                  className="relative w-full shrink-0 overflow-hidden rounded-xl border border-black/8 bg-[#06243B]"
                  style={{ aspectRatio: "9 / 16" }}
                >
                  <Image
                    src={`/img/clipper/styles/bundle-${s.id}.webp`}
                    alt={`Contoh klip gaya ${s.label} hasil render Clipper`}
                    fill
                    sizes="(min-width: 1024px) 22vw, 45vw"
                    className="object-cover"
                    unoptimized
                  />
                </div>
                {/* flex-1 + mt-auto so the render-time line lands on one
                    baseline across all four columns despite unequal copy.
                    Only from sm up: in the 2-column mobile grid the same trick
                    opens a dead gap under the shorter card instead. */}
                <div className="flex flex-1 flex-col gap-1">
                  <h3 className="text-[15px] font-extrabold text-[#06243B]">{s.label}</h3>
                  <p className="text-[13px] leading-relaxed text-[#3D4F60]">{s.body}</p>
                  <p className="pt-1 text-[12px] leading-relaxed text-[#3D4F60]/60 sm:mt-auto">
                    {s.speed}
                  </p>
                </div>
              </AnimatedSection>
            ))}
          </div>

          <div className="border-t border-black/8 pt-12 flex flex-col gap-8">
            <AnimatedSection className="mx-auto max-w-2xl text-center flex flex-col gap-2">
              <h3 className="text-xl sm:text-2xl font-extrabold text-[#06243B]">
                Delapan gaya caption, ganti kapan aja.
              </h3>
              <p className="text-[#3D4F60] leading-relaxed">
                Bisa diganti per klip, jadi gak harus ngunci satu gaya buat semua video. Font-nya
                Anton sama Montserrat, ikut dibundel di aplikasinya.
              </p>
            </AnimatedSection>

            <div className="grid grid-cols-2 lg:grid-cols-3 gap-5 sm:gap-6">
              {CAPTION_STYLES.map((c) => (
                <AnimatedSection key={c.id} className="flex flex-col gap-2">
                  <Image
                    src={`/img/clipper/styles/caption-${c.id}.webp`}
                    alt={`Contoh caption gaya ${c.label} hasil render Clipper`}
                    width={560}
                    height={180}
                    className="w-full h-auto rounded-lg border border-black/8 bg-[#06243B]"
                    unoptimized
                  />
                  <h4 className="text-[14px] font-extrabold text-[#06243B]">{c.label}</h4>
                </AnimatedSection>
              ))}
            </div>

            <AnimatedSection className="mx-auto max-w-2xl text-center">
              <p className="text-[#3D4F60]/70 text-sm leading-relaxed">
                Dua gaya lama dari versi sebelumnya juga masih ada, jadi klip yang udah kamu bikin
                tetap sama look-nya.
              </p>
            </AnimatedSection>
          </div>
        </div>
      </section>

      {/* Comparison */}
      <section className="bg-white py-20 sm:py-24">
        <div className="container-mote flex flex-col gap-12">
          <AnimatedSection className="mx-auto max-w-2xl text-center flex flex-col items-center gap-3">
            <span className="eyebrow">Sekali bayar vs langganan</span>
            <h2 className="text-[#06243B]">Kenapa punya sendiri lebih menang.</h2>
          </AnimatedSection>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto w-full">
            {/* Subscription */}
            <AnimatedSection className="rounded-2xl border border-black/10 bg-[#F7F8FA] p-8 flex flex-col gap-5">
              <h3 className="text-lg font-extrabold text-[#06243B]/70">Tool clip langganan bulanan</h3>
              <ul className="flex flex-col gap-3.5">
                {SUBSCRIPTION_CONS.map((t) => (
                  <li key={t} className="flex items-start gap-3 text-[#3D4F60]">
                    <span className="h-5 w-5 rounded-full bg-black/5 text-[#06243B]/40 flex items-center justify-center shrink-0 mt-0.5">
                      <X className="h-3 w-3" strokeWidth={3} />
                    </span>
                    <span className="text-[15px]">{t}</span>
                  </li>
                ))}
              </ul>
            </AnimatedSection>
            {/* Clipper */}
            <AnimatedSection className="relative rounded-2xl border-2 border-[#BDF24A] bg-white p-8 flex flex-col gap-5 shadow-[0_24px_60px_-30px_rgba(6,36,59,0.35)]">
              <span className="absolute -top-3 left-8 rounded-full bg-[#BDF24A] px-3 py-1 text-[11px] font-extrabold uppercase tracking-wide text-[#06243B]">
                Clipper by Mote
              </span>
              <h3 className="text-lg font-extrabold text-[#06243B]">Punya sendiri, sekali bayar</h3>
              <ul className="flex flex-col gap-3.5">
                {CLIPPER_PROS.map((t) => (
                  <li key={t} className="flex items-start gap-3 text-[#06243B]">
                    <span className="h-5 w-5 rounded-full bg-[#BDF24A] text-[#06243B] flex items-center justify-center shrink-0 mt-0.5">
                      <Check className="h-3 w-3" strokeWidth={3.5} />
                    </span>
                    <span className="text-[15px] font-semibold">{t}</span>
                  </li>
                ))}
              </ul>
            </AnimatedSection>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="bg-[#F7F8FA] py-20 sm:py-24 border-y border-black/5">
        <div className="container-mote flex flex-col gap-12">
          <AnimatedSection className="mx-auto max-w-2xl text-center flex flex-col items-center gap-3">
            <span className="eyebrow">Yang kamu dapat</span>
            <h2 className="text-[#06243B] max-sm:text-[1.375rem]">Semua buat produksi klip, sekali beli.</h2>
          </AnimatedSection>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {FEATURES.map((f) => {
              const Icon = f.icon;
              return (
                <AnimatedSection
                  key={f.title}
                  className="rounded-2xl border border-black/8 bg-white p-7 flex flex-col gap-3 h-full"
                >
                  <div className="h-11 w-11 rounded-xl bg-[#BDF24A]/20 flex items-center justify-center text-[#06243B]">
                    <Icon className="h-5 w-5" strokeWidth={2.2} />
                  </div>
                  <h3 className="text-base font-extrabold text-[#06243B]">{f.title}</h3>
                  <p className="text-[#3D4F60] leading-relaxed text-[15px]">{f.body}</p>
                </AnimatedSection>
              );
            })}
          </div>
        </div>
      </section>

      {/* Buy */}
      <section id="beli" className="bg-white py-20 sm:py-24">
        <div className="container-mote grid grid-cols-1 lg:grid-cols-2 gap-10 lg:gap-16 items-center">
          <AnimatedSection className="flex flex-col gap-5">
            <span className="eyebrow">Beli sekali, punya selamanya</span>
            <h2 className="text-[#06243B] max-sm:text-[1.375rem]">
              Satu kali <span className="highlight-text">{PRICE}</span>. Tanpa langganan.
            </h2>
            <p className="text-[#3D4F60] leading-relaxed text-lg">
              Setara harga sekali ngopi. Isi data, bayar, dan lisensi + panduan install langsung
              dikirim ke email kamu.
            </p>
            <ul className="flex flex-col gap-2.5 mt-1">
              {[
                "Lisensi seumur hidup — tanpa biaya bulanan",
                "Render klip tanpa batas",
                "Jalan lokal, video kamu tetap privat",
                "4 paket gaya, 8 caption, 3 mode framing",
                "Brand sendiri (nama, logo, warna)",
              ].map((b) => (
                <li key={b} className="flex items-center gap-3 text-[#06243B] font-medium">
                  <span className="h-5 w-5 rounded-full bg-[#BDF24A] text-[#06243B] flex items-center justify-center shrink-0">
                    <Check className="h-3 w-3" strokeWidth={3.5} />
                  </span>
                  {b}
                </li>
              ))}
            </ul>
            <a
              href="/products/clipper/setup"
              className="inline-flex items-center gap-1.5 text-sm font-semibold text-[#06243B]/60 hover:text-[#06243B] mt-1 self-start"
            >
              Sudah beli? Lihat panduan setup
              <ChevronRight className="h-4 w-4" />
            </a>
          </AnimatedSection>
          <AnimatedSection>
            <CheckoutForm />
          </AnimatedSection>
        </div>
      </section>

      {/* FAQ */}
      <section id="faq" className="bg-[#F7F8FA] py-20 sm:py-24 border-t border-black/5 scroll-mt-24">
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
        />
        <div className="container-mote max-w-3xl flex flex-col gap-10">
          <AnimatedSection className="flex flex-col gap-3">
            <span className="eyebrow">FAQ</span>
            <h2 className="text-[#06243B]">Pertanyaan yang sering muncul.</h2>
          </AnimatedSection>
          <div className="flex flex-col gap-3">
            {FAQS.map((f, i) => (
              <AnimatedSection key={f.q} delay={i * 0.04}>
                <details className="group rounded-2xl border border-black/8 bg-white overflow-hidden">
                  <summary className="flex items-center justify-between gap-4 cursor-pointer list-none p-5 sm:p-6 [&::-webkit-details-marker]:hidden">
                    <h3 className="text-base font-extrabold text-[#06243B]">{f.q}</h3>
                    <ChevronDown className="h-5 w-5 shrink-0 text-[#06243B]/50 transition-transform group-open:rotate-180" />
                  </summary>
                  <div className="px-5 sm:px-6 pb-5 sm:pb-6 flex flex-col items-start gap-3">
                    <p className="text-[#3D4F60] leading-relaxed">{f.a}</p>
                    {f.more && (
                      <Link
                        href={f.more.href}
                        className="inline-flex items-center gap-1.5 text-sm font-bold text-[#06243B] underline underline-offset-4 decoration-[#BDF24A] decoration-2 hover:decoration-[#06243B] transition-colors"
                      >
                        {f.more.label}
                        <ArrowRight className="h-3.5 w-3.5" />
                      </Link>
                    )}
                  </div>
                </details>
              </AnimatedSection>
            ))}
          </div>
          <AnimatedSection className="flex flex-col sm:flex-row items-start sm:items-center gap-4 justify-between rounded-2xl bg-[#06243B] p-7">
            <div>
              <p className="text-white font-extrabold text-lg">Masih ragu cocok atau tidak?</p>
              <p className="text-white/70">Chat dulu — kami jujur bilang cocok atau tidak buat kamu.</p>
            </div>
            <a
              href={CONTACT.whatsappLink}
              target="_blank"
              rel="noopener noreferrer"
              className="btn btn-primary group shrink-0"
            >
              Chat via WhatsApp
              <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
            </a>
          </AnimatedSection>
        </div>
      </section>
    </>
  );
}
